name: "Compile for Windows and MacOS"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version: 20

      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/client/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('client/**/package-lock.json') }}-${{ hashFiles('client/**/*.[jt]s', 'client/**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('client/**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci && cd client && npm ci
        shell: cmd

      - name: Run packing action
        run: npm run pack

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
            name: Windows Build Output
            path: dist/*.exe
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version: 20

      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/client/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('client/**/package-lock.json') }}-${{ hashFiles('client/**/*.[jt]s', 'client/**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('client/**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci && cd client && npm ci

      - name: "Run packing action"
        run: npm run pack

      - name: "Upload files"
        uses: actions/upload-artifact@v4
        with:
            name: MacOS Build Output
            path: |
              dist/*.dmg
              dist/*.zip
    
