name: "Compile for Windows and MacOS"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version: 20

      - name: Install dependencies
        run: npm install && cd client && npm install

      - name: Run packing action
        run: npm run pack

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
            name: Installer & Portable
            path: dist/*.exe
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version: 20

      - name: Install dependencies
        run: npm install && cd client && npm install

      - name: "Run packing action"
        run: npm run pack

      - name: "Upload files"
        uses: actions/upload-artifact@v4
        with:
            name: "Installer & Portable"
            path: |
              dist/*.dmg
              dist/*.zip
    
